### ISSUE TITLE
Improvement in EvalAI Frontend

### ISSUE THREAD

**Issue by Sanji515** [Cloud-CV/GSoC-Ideas#28]
**Project Title:** Improvement in EvalAI frontend

**Description:**

As a part of last year’s GSOC, we took the first step towards modernizing our UI which involved shifting the current codebase from Angular 1 to Angular 7. As we’ve reached the feature parity with the existing UI, this project will involve fixing the last remaining kinks in the UI and incorporating latest UI feedback which we have received from the challenge hosts and participants for the AI challenges organized this year. The goal of this project would be to successfully replace the existing UI with the new UI after GSOC.

**Deliverable:**

- [ ] Add features to participate in a challenge based on the invitation by the challenge host. 
- [ ] Add testimonials, statistics on the home page
- [ ] Enhance the UI for displaying the submissions under My submission Tab & View all submissions Tab
- [ ] Add feature for prettier URLs for the challenge.
- [ ] Add support for editing challenge details.
- [ ] Add CRUD feature to challenge host on submissions
- [ ] Add pages for maintenance, 400, 500, 404 errors on the website.
- [ ] Add feature for filtering the challenges on UI
- [ ] Add features to export submissions in different formats by the challenge hosts for analysis.
- [ ]  Add service workers for making the website loading faster.

**Mentor:** Sanjeev Singh @Sanji515 , Mayank @lunayach , Shekhar Prasad Rajak @Shekharrajak,  Rishabh Jain @RishabhJain2018 

**Skills:** Angular 7, HTML, CSS, Typescript

**Skill Level:** Medium

**Get started:** Try to fix some issues in EvalAI (note that there are some issues labeled with GSOC-2020)

**Tutorials:**

- https://angular.io/tutorial
- https://www.tutorialspoint.com/angular7/index.htm

**Important Links:**

- EvalAI Website: [evalai.cloudcv.org](https://evalai.cloudcv.org/)
- EvalAI-ngx Github repository: [Cloud-CV/EvalAI](https://github.com/Cloud-CV/EvalAI-ngx)
- EvalAI Docs: [http://evalai.readthedocs.io/en/latest](http://evalai.readthedocs.io/en/latest)
- GSoC Proposal Template: [Cloud-CV/GSoC-Ideas/wiki/GSOC-2020-Proposal-Template](https://github.com/Cloud-CV/GSoC-Ideas/wiki/GSOC-2020-Proposal-Template)
- Gitter Channel: [gitter.im/Cloud-CV](https://gitter.im/Cloud-CV/)
- Mailing list: [groups.google.com/forum/#!forum/cloudcv](https://groups.google.com/forum/#!forum/cloudcv)

**Comment by Kajol-Kumari** [comment]
Hello Mentors! @Sanji515 @RishabhJain2018 @lunayach. I would like to work on this as a part of GSOC'20.

**Comment by Sanji515** [comment]
Thanks @Kajol-Kumari for your interest. Looking forward to your contributions and GSOC proposal.

**Comment by Shekharrajak** [comment]
Just want to add few important things in the above task list: 

* Last year GSoC (2019) we worked on upgrading the Angular version to 7. It is always good to upgrade the version because it comes with new features, improvements in performance. We can see that [Angular 9 is out](https://blog.angular.io/version-9-of-angular-now-available-project-ivy-has-arrived-23c97b63cfa3) so we should work on to upgrade the version. It will definitely improve the performance and if we are implementing a new feature then we will make sure to use the latest version of dependencies.

 * To make it robust and modular, we should define custom directives and pipes rather than using piece of code again and again. For example, [if condition to check the user is authenticated or not](https://github.com/Cloud-CV/EvalAI-ngx/blob/master/src/app/components/nav/header-static/header-static.component.html#L7), is repeating many times in most of the pages/subpage. Instead of the if condition we can have a directive that will validate the user and put css/class (in this case hiding the content). Actually we should avoid logic in templates itself. So we can work on the refactoring part.

* Improve the [test coverage](https://codecov.io/gh/Cloud-CV/EvalAI-ngx), which is around 50% now. We should keep adding test cases along with enhancements and changes. Writing missing documentation for the methods.

* Currently we have only one module [app.module](https://github.com/Cloud-CV/EvalAI-ngx/blob/master/src/app/app.module.ts), that declares all the components, provide all the services. Students can come up with some ideas to divide it and make small/independent modules. Then import it in base module (which is app.module) this will improve the application code base and quality.


I will add a few more points/ideas once I make sure those changes will reduce the complexity of the application.

Suggestions and comments are welcome in above points. WDYT @Sanji515 , @lunayach , @RishabhJain2018

**Comment by Kajol-Kumari** [comment]
> Thanks @Kajol-Kumari for your interest. Looking forward to your contributions and GSOC proposal.

@Sanji515 Can you please help me to clarify whether you are taking about the contribution related to this particular idea or any contribution related to EvalAI?

**Comment by RishabhJain2018** [comment]
Hi @Kajol-Kumari ,
> Can you please help me to clarify whether you are taking about the contribution related to this particular idea or any contribution related to EvalAI?

If you're planning to submit a proposal for this idea, we would like to see a few contributions in EvalAI-ngx (for frontend) repository along with EvalAI (for backend).

**Comment by Kajol-Kumari** [comment]
> Hi @Kajol-Kumari ,
> 
> > Can you please help me to clarify whether you are taking about the contribution related to this particular idea or any contribution related to EvalAI?
> 
> If you're planning to submit a proposal for this idea, we would like to see a few contributions in EvalAI-ngx (for frontend) repository along with EvalAI (for backend).

Okay @RishabhJain2018 . Thank you for clarification.

**Comment by sseth99** [comment]
Hello Mentors and participants! 
I would like to work with CloudCV on this project as a part of GSoc' 2020.

**Comment by sraghuvanshi** [comment]
Hi Mentors!  @RishabhJain2018 @Sanji515 @lunayach
Hope you'll are having a great day 💯 

First of all congratulations and thank you all for working on such a great initiative. EvalAI is a great project, it really standardize the process of evaluating different methods on a dataset and makes it easier to host a competition. 

I'm a sophomore, studying in JSS, Noida. I'm a member of Nibble Computer Society. We at NCS really admire our alumni's @RishabhJain2018 sir and @deshraj sir for setting a benchmark.

This project seems very exciting to me. It is great to know that you people are focusing on user experience because I believe that **to the users the interface is the product**. I would love to contribute in this project.

**Comment by RishabhJain2018** [comment]
Hi @sseth99 & @sraghuvanshi, Welcome to CloudCV! Looking forward to your contributions and GSoC Proposal.

**Comment by the-utkarshjain** [comment]
Hi mentors! @Sanji515 @RishabhJain2018 @Shekharrajak @lunayach 
I'm Utkarsh Jain, a third-year student at IIT Mandi and I'm interested to contribute to EvalAI. Just one doubt. Is it mandatory to fix an issue labeled with GSOC-2020 or can I fix any open issue?

**Comment by lunayach** [comment]
Hi @the-utkarshjain! Feel free to open a relevant issue and fix it. Looking forward to your proposal!

**Comment by danielrs975** [comment]
Hi mentors, @Sanji515 @RishabhJain2018  @Shekharrajak  @lunayach  I'm Daniel Rodriguez, a first year master in Computer Science Student at Télécom SudParis, France. I'm really interested in participating in this project. Where can I see the open issues for this project?

**Comment by Shekharrajak** [comment]
Hi @danielrs975 , Happy to hear that you are interested for the project. I hope you have read the idea description and understood the overview of the project . You can find the the repo link in description: https://github.com/Cloud-CV/EvalAI-ngx 

You can see the open issues and pick (may be easy to fix issue first), to understand the codebase after you go through the [development setup](https://github.com/Cloud-CV/EvalAI-ngx#development-setup) and [contribution guideline](https://github.com/Cloud-CV/EvalAI-ngx#contributing). 

It is worth seeing the backend part as well, here: https://github.com/Cloud-CV/EvalAI 

Hope these links will help you. Keep committing :)

**Comment by Kajol-Kumari** [comment]
Along with breaking down the main app-module, we should also keep the separate routes for the modules as currently [app-module](https://github.com/Cloud-CV/EvalAI-ngx/blob/master/src/app/app-routing.module.ts) module contains all the routes as it will make the routing file cleaner and organized.

Also currently, the pagination is not working in the participants an host page. So, we can implement this feature under GSOC'20 by adding this in the features list.

In addition to service worker, we can also include lazy loading in our routes in order to further enhance the performance of the website.

cc: @Sanji515 @lunayach @RishabhJain2018 @Shekharrajak 
please let me know your views on this.

**Comment by Shekharrajak** [comment]
> Along with breaking down the main app-module, we should also keep the separate routes for the modules as currently [app-module](https://github.com/Cloud-CV/EvalAI-ngx/blob/master/src/app/app-routing.module.ts) module contains all the routes as it will make the routing file cleaner and organized.
> 
> Also currently, the pagination is not working in the participants an host page. So, we can implement this feature under GSOC'20 by adding this in the features list.
> 
> In addition to service worker, we can also include lazy loading in our routes in order to further enhance the performance of the website.
> 
> cc: @Sanji515 @lunayach @RishabhJain2018 @Shekharrajak
> please let me know your views on this.

Thanks for noting down the points. It would be great if you try out (or open a discussion issue) each of the tasks. You can discuss your implementation plan there (or may be open  a  WIP tag PR), to show case rough idea what & how you want to achieve it.

Keep committing :)

**Comment by Shekharrajak** [comment]
Same comment as here: https://github.com/Cloud-CV/GSoC-Ideas/issues/26#issuecomment-602010186

Hello, Students! 

I am continuously getting messages in different platforms(linkedin/gitter, etc) about the application review or discussion. It would be better if student create a mail thread in google group: https://groups.google.com/forum/#!forum/cloudcv and cc all the mentors. It will help to know everyone about the idea, proposal and we can easily correct you or provide the right direction to your approach.

Keep committing! :)
