### ISSUE TITLE
Adversarial Data using Gradio and EvalAI

### ISSUE THREAD

**Issue by gchhablani** [Cloud-CV/GSoC-Ideas#57]
**Project Title:** Adversarial Data using Gradio and EvalAI

**Description:** The aim of this project is to develop an infrastructure that enables the collection of adversarial data for models submitted to EvalAI. This will be achieved by integrating Gradio with EvalAI's code upload challenge pipeline and deploying the models as web services. The web services will record all user interactions, providing a dataset for each submission that can be used to evaluate the robustness of the model.

**Deliverable:**
- [ ] Build system design for EvalAI and Gradio integration
- [ ] Setup Gradio integration for a single VQA demo as a proof of concept
  - [ ] Create a Gradio interface wrapper that is modular for model inputs
  - [ ] Integrate the gradio interface with dockerized model for inference
- [ ] Setup auto launching of a worker service for deploying a Gradio app using a celery task from EvalAI django backend.
- [ ] Add frontend controls to deploy a Gradio web service for a single submission made by a participant to a code upload challenge.
- [ ] Add support to log interactions made by a user on the Gradio web service and push the interactions to a database table specific to a demo.
- [ ] Add API support to export the logged interactions for a demo.
- [ ] Implement frontend changes to allow users to download the logged interactions in a standard dataset format.

**Mentor:** Rishabh Jain, Ram Ramrakhya

**Skills:** Python, Django, AngularJS, AWS

**Skill Level:** Hard

**Get started:** Try to fix some issues in EvalAI (note that there are some issues labeled with GSOC-2023)

**Important Links**:
- EvalAI Website: [eval.ai](https://eval.ai/)
- EvalAI Github repository: [Cloud-CV/EvalAI](https://github.com/Cloud-CV/EvalAI)
- EvalAI Docs: http://evalai.readthedocs.io/en/latest
- GSoC Proposal Template: [Cloud-CV/GSoC-Ideas/wiki/GSOC-2020-Proposal-Template](https://github.com/Cloud-CV/GSoC-Ideas/wiki/GSOC-2020-Proposal-Template)
- Gitter Channel: [gitter.im/Cloud-CV](https://gitter.im/Cloud-CV/)
- Mailing list: [groups.google.com/forum/#!forum/cloudcv](https://groups.google.com/forum/#!forum/cloudcv)

**Comment by ashutosh887** [comment]
I would like to work on this @Ram81 for GSOC

**Comment by thesakshidiggikar** [comment]
@Ram81 could you pleaser provide gitter channel the above given link is showing me an error

**Comment by marinicadenisandrei** [comment]
Hi Gunjan and Ram,

I am very interested in participating for the "Adversarial Data using Gradio and EvalAI " program offered by GSOC 2023.

I am very passionate about this field, I currently work for companies that use the same technologies and I am also a master's student with a profile focused on these technologies. I would like to interact with a very well developed team, from which I can learn a lot of things and to be able to interact and implement all the knowledge to contribute to this project.

I am very passionate, I want to devote myself a lot to the project and to be able to participate in this GSOC 2023 program.

**Comment by marinicadenisandrei** [comment]
Hi,

I am very interested in participating for the "Adversarial Data using Gradio and EvalAI" program offered by GSOC 2023.

I am very passionate about this field, I currently work for companies that use the same technologies and I am also a master's student with a profile focused on these technologies. I would like to interact with a very well developed team, from which I can learn a lot of things and to be able to interact and implement all the knowledge to contribute to this project.

I am very passionate, I want to devote myself a lot to the project and to be able to participate in this GSOC 2023 program.

**Comment by danush754** [comment]
Hello CloudCv team,
I'm really interested in the "Adversarial Data using Gradio and EvalAI" program for GSOC 2023, and I'd love to represent CloudCV. Even though I don't have any previous experience with Flask, Gradio, or EvalAI, I'm eager to learn and contribute. I'm a quick learner, and I'm passionate about the project and the opportunity to work on cutting-edge research. If you're looking for someone who's motivated and ready to dive in, I'm your person. Thankyou!

**Comment by marinicadenisandrei** [comment]
> 
Basic details
_____________________________________________________________________________________
My name is Marinica Denis Andrei, I live in Bucharest, Romania, Eastern European Time (GMT+2). As a bachelor's degree, I graduated from the Polytechnic University of Bucharest, Faculty of Industrial Engineering and Robotics, "Robotics and Computer Science" department, the final grade obtained being 9.5/10, having as a diploma project the realization of a robotic cell for depalletizing, labeling and repalletizing of cardboard boxes integrating an ABB IRB 760 articulated arm industrial robot from the ABB company. To complete the diploma project, I realized the 3D simulation of the entire robotic cell using a microcontroller from the ABB company, internet networks and signals created in the ABB Robot Studio software. I made the simulation using python and C# scripts. We also made a matrix of accelerations and rotations for the integrated robot, calculations of tangential and centrifugal forces made in Matlab and an automatic tracking system made in python.

I am currently a master's student at the Polytechnic University of Bucharest, at the Faculty of Automation and Computer Science, majoring in "Computer Science, Advanced Control and Real-Time Systems", the grade obtained in the entrance exam being 10/10. I have already started the dissertation project, continuing the bachelor's project. This project involves the realization of the physically articulated arm type robot, the components being made through the additive manufacturing process (3D printing), integrating Arduino components and servomotors. For this robot, I started programming two offline and online applications. The programming of the industrial robot is done through the Arduino IDE and the C programming language, the robot having commands that it can take from the serial bus. The offline application is made with the Python programming language, having several panels that can interact with the operating system and CAD-type programs, tracking signals, positions that can be transposed in graphic form, control of individual servomotors and the control carried out on coordinate axes correlating several servomotors to achieve the movement. I have also integrated an online application, an application created as a back-end using the Python programming language, the Flask library, Jinja, pyserial (for transmitting serial signals to the robot), mathplotlib (for making graphs), pandas, numpy (for reading a document with a code already registered for programming the robot), SQL and pylogin (for the registration in a database of each account created on the online application), various APIs for webscraping of information displayed in real time from (Google search , google scholar, youtube, google patents), BS4 and Selenium for webdriver automation and information retrieval through webscraping. Also, the front-end part is made through HTML, CSS, SASS, JS, Bootstrap5, MediaQuery. The application also has an authentication and creation system for user accounts and a 2-factor authentication system, through which the user enters the email address and receives an automatic verification code.

I currently work as a System Engineer in the Continental Automotive company, ADAS Autonomus Mobility department. The technologies used are C, C++, Python, CAN, SPI, ETHERNET. On the requirements side, I use IMS, Jira, Confluence, DOORS NG, Jazz. I am assigned to 3 different projects, 50 percent I work on the "Market Intelligence and Concept Development" project, it involves the analysis of the global market and products for the improvement of Continental products, the creation of scripts with trend and seasonal data prediction algorithms, the creation system architecture (hardware and software), extracting data from the Internet and filtering them through webscraping technology and creating relevant charts for market analysis. All this is done through Python, C and Matlab languages.

For the rest of the projects, I am assigned 25 percent each, the first one being "camera, ultrasonic and satellites", realizing the software and hardware architecture together with the domains, and the other project being (DeepDrive) for which I analyze the image from the camera at the pixel level, detection, distances with Python and C.

In the past I worked as a Software Test Automation Engineer in the Luxoft company for the creation of a camera for detection, processing and transmission of signals to the ECU. I analyze exports from the script based on a test plan. The csv exports were the values of all CAN and SPI signals for each frame. Also, with each software release, we inject new software by flashing the camera, test and realize certain events in Canoe and create automatic testing scripts, automatic flashing.

Statement of Motivation
_____________________________________________________________________________________
My motivation comes from my passion for the software field, all my hobbies are related to this field, I have always tried to occupy my time developing my programming knowledge, I constantly follow courses for programming, computer science, I constantly do problems on leetcode for C , JS and Python to practice my logical thinking and develop a lot.

I really want to be accepted in the Google Summer of Code program because I want to develop myself, I want to learn as much as possible to have a very solid portfolio of projects and experience and to be able to apply all the knowledge I have. I am very excited because I have this opportunity, I want to be the best in what I do and satisfy my boundless passion for software and technology.

The programming languages and technologies I am passionate about are python, django, docker, angularjs, aws, machine learning, artificial intelligence, computer vision, deep learning, AI/ML. I want to be part of this organization because I really like the technologies you use, I want to develop myself in this part of machine learning and artificial intelligence, to be able to interact with as many experts as possible and to be able to participate in the development of an important project in this organization.

Following this organization and this project, I want to accumulate a lot of experience, learn a lot and interact with technologies and projects and be able to interact with the thinking of experts in this field.
Experiences
_____________________________________________________________________________________

My experience in this direction is accumulated both from the jobs I had and from the educational institutions I attend and from which I graduated.
Constantly, since high school, I followed a lot of trainings on programming, computer science, machine learning, artificial intelligence, but also a lot of tests for certifications.

Courses:
- Udemy - Course - 100 Days of Code: The Complete Python Pro Bootcamp
- Udemy - Course - Python Programming
- Udemy - Course - The Python Bible
- Udemy - Course - C++
- Udemy – Course – C Programming for beginners – Master the C language (in progress)
- CS50 Introduction to Computer Science – Harvard University (in progress)
- Luxoft course – Python Basic
- Luxoft course – Professional Python
- Luxoft course – Introduction to Git
- Luxoft course – Advanced C programming pointers
- Luxoft course – C++ High Performance
- Luxoft course – Open Source Software
- Luxoft course – Software Test Design
- Luxoft course – ASPICE/DQMS


Certifications:
- freeCodeCamp - Scientific Computing with Python
- HIL Academy – Test Automation
- C# -  LinkedIn Skill Assessment badge
- C (Programming Language) -  LinkedIn Skill Assessment badge
- Machine Learning -  LinkedIn Skill Assessment badge
- IT Operations - LinkedIn Skill Assessment badge
- MATLAB -  LinkedIn Skill Assessment badge
- Object-Oriented Programming (OOP) -  LinkedIn Skill Assessment badge
- Agile Methodologies -  LinkedIn Skill Assessment badge
- Git -  LinkedIn Skill Assessment badge
- Python (Programming Language) -  LinkedIn Skill Assessment badge
- ISTQB Certified Tester Foundation
- AUTOSAR Classic Fundamentals
Project details
_____________________________________________________________________________________
I would like to be part of a project that uses an advanced technology because I really like challenges, I want to learn as much as possible to interact as much as possible with advanced algorithms and structures and to interact with an advanced mentor and expert in the field. I would really like to be able to talk to an expert to choose the best possible project that will represent the best possible experience for me.

Regarding the time I want to allocate, I want to get involved in the development of the project and to work every day from Monday to Sunday and during work hours and after work hours, of course also on weekends. Time is not a problem for me, I want to devote myself as much as possible and learn as many things as possible because, as I said, I am passionate.

**Comment by marinicadenisandrei** [comment]
Basic details
_____________________________________________________________________________________
My name is Marinica Denis Andrei, I live in Bucharest, Romania, Eastern European Time (GMT+2). As a bachelor's degree, I graduated from the Polytechnic University of Bucharest, Faculty of Industrial Engineering and Robotics, "Robotics and Computer Science" department, the final grade obtained being 9.5/10, having as a diploma project the realization of a robotic cell for depalletizing, labeling and repalletizing of cardboard boxes integrating an ABB IRB 760 articulated arm industrial robot from the ABB company. To complete the diploma project, I realized the 3D simulation of the entire robotic cell using a microcontroller from the ABB company, internet networks and signals created in the ABB Robot Studio software. I made the simulation using python and C# scripts. We also made a matrix of accelerations and rotations for the integrated robot, calculations of tangential and centrifugal forces made in Matlab and an automatic tracking system made in python.

I am currently a master's student at the Polytechnic University of Bucharest, at the Faculty of Automation and Computer Science, majoring in "Computer Science, Advanced Control and Real-Time Systems", the grade obtained in the entrance exam being 10/10. I have already started the dissertation project, continuing the bachelor's project. This project involves the realization of the physically articulated arm type robot, the components being made through the additive manufacturing process (3D printing), integrating Arduino components and servomotors. For this robot, I started programming two offline and online applications. The programming of the industrial robot is done through the Arduino IDE and the C programming language, the robot having commands that it can take from the serial bus. The offline application is made with the Python programming language, having several panels that can interact with the operating system and CAD-type programs, tracking signals, positions that can be transposed in graphic form, control of individual servomotors and the control carried out on coordinate axes correlating several servomotors to achieve the movement. I have also integrated an online application, an application created as a back-end using the Python programming language, the Flask library, Jinja, pyserial (for transmitting serial signals to the robot), mathplotlib (for making graphs), pandas, numpy (for reading a document with a code already registered for programming the robot), SQL and pylogin (for the registration in a database of each account created on the online application), various APIs for webscraping of information displayed in real time from (Google search , google scholar, youtube, google patents), BS4 and Selenium for webdriver automation and information retrieval through webscraping. Also, the front-end part is made through HTML, CSS, SASS, JS, Bootstrap5, MediaQuery. The application also has an authentication and creation system for user accounts and a 2-factor authentication system, through which the user enters the email address and receives an automatic verification code.

I currently work as a System Engineer in the Continental Automotive company, ADAS Autonomus Mobility department. The technologies used are C, C++, Python, CAN, SPI, ETHERNET. On the requirements side, I use IMS, Jira, Confluence, DOORS NG, Jazz. I am assigned to 3 different projects, 50 percent I work on the "Market Intelligence and Concept Development" project, it involves the analysis of the global market and products for the improvement of Continental products, the creation of scripts with trend and seasonal data prediction algorithms, the creation system architecture (hardware and software), extracting data from the Internet and filtering them through webscraping technology and creating relevant charts for market analysis. All this is done through Python, C and Matlab languages.

For the rest of the projects, I am assigned 25 percent each, the first one being "camera, ultrasonic and satellites", realizing the software and hardware architecture together with the domains, and the other project being (DeepDrive) for which I analyze the image from the camera at the pixel level, detection, distances with Python and C.

In the past I worked as a Software Test Automation Engineer in the Luxoft company for the creation of a camera for detection, processing and transmission of signals to the ECU. I analyze exports from the script based on a test plan. The csv exports were the values of all CAN and SPI signals for each frame. Also, with each software release, we inject new software by flashing the camera, test and realize certain events in Canoe and create automatic testing scripts, automatic flashing.

Statement of Motivation
_____________________________________________________________________________________
My motivation comes from my passion for the software field, all my hobbies are related to this field, I have always tried to occupy my time developing my programming knowledge, I constantly follow courses for programming, computer science, I constantly do problems on leetcode for C , JS and Python to practice my logical thinking and develop a lot.

I really want to be accepted in the Google Summer of Code program because I want to develop myself, I want to learn as much as possible to have a very solid portfolio of projects and experience and to be able to apply all the knowledge I have. I am very excited because I have this opportunity, I want to be the best in what I do and satisfy my boundless passion for software and technology.

The programming languages and technologies I am passionate about are python, django, docker, angularjs, aws, machine learning, artificial intelligence, computer vision, deep learning, AI/ML. I want to be part of this organization because I really like the technologies you use, I want to develop myself in this part of machine learning and artificial intelligence, to be able to interact with as many experts as possible and to be able to participate in the development of an important project in this organization.

Following this organization and this project, I want to accumulate a lot of experience, learn a lot and interact with technologies and projects and be able to interact with the thinking of experts in this field.
Experiences
_____________________________________________________________________________________

My experience in this direction is accumulated both from the jobs I had and from the educational institutions I attend and from which I graduated.
Constantly, since high school, I followed a lot of trainings on programming, computer science, machine learning, artificial intelligence, but also a lot of tests for certifications.

Courses:
- Udemy - Course - 100 Days of Code: The Complete Python Pro Bootcamp
- Udemy - Course - Python Programming
- Udemy - Course - The Python Bible
- Udemy - Course - C++
- Udemy – Course – C Programming for beginners – Master the C language (in progress)
- CS50 Introduction to Computer Science – Harvard University (in progress)
- Luxoft course – Python Basic
- Luxoft course – Professional Python
- Luxoft course – Introduction to Git
- Luxoft course – Advanced C programming pointers
- Luxoft course – C++ High Performance
- Luxoft course – Open Source Software
- Luxoft course – Software Test Design
- Luxoft course – ASPICE/DQMS


Certifications:
- freeCodeCamp - Scientific Computing with Python
- HIL Academy – Test Automation
- C# -  LinkedIn Skill Assessment badge
- C (Programming Language) -  LinkedIn Skill Assessment badge
- Machine Learning -  LinkedIn Skill Assessment badge
- IT Operations - LinkedIn Skill Assessment badge
- MATLAB -  LinkedIn Skill Assessment badge
- Object-Oriented Programming (OOP) -  LinkedIn Skill Assessment badge
- Agile Methodologies -  LinkedIn Skill Assessment badge
- Git -  LinkedIn Skill Assessment badge
- Python (Programming Language) -  LinkedIn Skill Assessment badge
- ISTQB Certified Tester Foundation
- AUTOSAR Classic Fundamentals
Project details
_____________________________________________________________________________________
I would like to be part of a project that uses an advanced technology because I really like challenges, I want to learn as much as possible to interact as much as possible with advanced algorithms and structures and to interact with an advanced mentor and expert in the field. I would really like to be able to talk to an expert to choose the best possible project that will represent the best possible experience for me.

Regarding the time I want to allocate, I want to get involved in the development of the project and to work every day from Monday to Sunday and during work hours and after work hours, of course also on weekends. Time is not a problem for me, I want to devote myself as much as possible and learn as many things as possible because, as I said, I am passionate.

**Comment by skat00sh** [comment]
Hi @gchhablani 
Congratulations to the CLoud-CV team on getting selected for Gsco'23 once again :) 
Little query: I tried searching for issues labelled `gsoc-2023` in the [Eval-AI/Issues](https://github.com/Cloud-CV/EvalAI/issues) but couldn't find any. Are they yet to be created? OR  may be I'm searching incorrectly. Not sure!

**Comment by DhruvChaurasia3418** [comment]
Hello @gchhablani, I would like to work on this project, can you assign it to me

**Comment by gchhablani** [comment]
@skat00sh @danush754 @ashutosh887 @DhruvChaurasia3418 @thesakshidiggikar @marinicadenisandrei 

Thank you for reaching out to us regarding the Google Summer of Code (GSoC) 2023 program. We appreciate your interest in our project and we are excited to have you as a potential participant.

As you may have seen, we have some open issues that we are looking into for both EvalAI and EvalAI-CLI. You can find them on our Github page at the following links:

- On EvalAI: https://github.com/Cloud-CV/EvalAI/issues?q=is%3Aissue+is%3Aopen+label%3AGSoC-2023
- On EvalAI-CLI: https://github.com/Cloud-CV/evalai-cli/issues/342

We encourage you to experiment with EvalAI and report any issues that you come across. We will be posting more issues soon, so stay tuned for those.

We have a Slack workspace that you can join to connect with other interested participants. Here's the link to join: https://join.slack.com/t/cloudcv-community/shared_invite/zt-1rkm0m8pw-TBkjRjx~_GyIvMVlF5iDHg

Once you're in, you can join the #gsoc-23-interested-participants channel to stay up to date on the latest news and discuss the project with other potential participants.

In the meantime, we encourage you to set up EvalAI locally and continue revising your proposal before the final deadline. If you have any questions or concerns, don't hesitate to reach out to us.

Hi, and welcome to the CloudCV community!

Best regards,

Gunjan Chhablani

**Comment by ashutosh887** [comment]
Thanks a lot @gchhablani for considering
Have a great day 😊

**Comment by chiragbiradar** [comment]
Hello @gchhablani ,

I am very interested in participating in the “Adversarial Data using Gradio and EvalAI” program offered by GSOC 2023. I am a Bachelors student with a profile focused on techs like cloud ,AI, devops, etc. I would like to join the Cloud-CV team from which I can learn and contribute to this project.
I am eager to devote myself to the project and participate in GSOC 2023 program.

**Comment by gchhablani** [comment]
@chiragbiradar Please join our Community Slack: https://join.slack.com/t/evalai-gsoc/shared_invite/zt-1rkm0m8pw-TBkjRjx~_GyIvMVlF5iDHg

**Comment by manya954** [comment]
Hello @gchhablani 
I am really interested in this project. I am a Bachelor's degree student with experience in web development, UX designing, C/C++, cloud, and Python please consider me for this opportunity.

**Comment by Manavkondagurle** [comment]
Hi,

I am very interested in participating for the "Adversarial Data using Gradio and EvalAI" program offered by GSOC 2023.

I am very passionate about this field, I currently work for companies that use the same technologies and I am also a master's student with a profile focused on these technologies. I would like to interact with a very well developed team, from which I can learn a lot of things and to be able to interact and implement all the knowledge to contribute to this project.

I am very passionate, I want to devote myself a lot to the project and to be able to participate in this GSOC 2023 program.

**Comment by Amitesh220** [comment]
Hello Mentors, I am Currently a pre final year student Working as a MERN stack developer intern , I am also learning DevOps to pursue my career in I am an open source enthusiast and looking forward to contribute to your projects Please guide me Further.
I truly want to devote myself in this project ,So please try to consider me for this project.
